name: Publish (dev)

on:
  push:
    tags:
      - "v*-dev*"

jobs:
  tagged_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@synapseprotocol"

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Build
        run: yarn run build

      - name: Set tagname in env
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Make tarball
        run: yarn pack --filename synapseprotocol-sdk-${{ steps.vars.outputs.tag }}.tgz

      - name: Create release with tarball
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: "dev"
          files: |
            synapseprotocol-sdk-${{ steps.vars.outputs.tag }}.tgz
            LICENSE
            README.md

      - name: Publish to NPM
        run: yarn publish --non-interactive --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SERVICE_ACCOUNT_TOKEN }}